/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testuebungen.testClient1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;


/**
 *
 * @author primus
 */
public class GUIClient extends javax.swing.JFrame
{
  private final String url = "localhost";
  private final String port = "9999";
  private CarList carlist;
  private ClientListModel clm;
  /**
   * Creates new form GUIClient
   */
  public GUIClient ()
  {
    initComponents();
    clm = new ClientListModel(carlist);
    jTable1.setModel(clm);
  }
  

  private void getCar()
  {
    String receivedCar[] = new String[3];
    Socket socket = new Socket();
    try
    {
      SocketAddress add = new InetSocketAddress(url, Integer.parseInt(port));
      socket.connect(add, 200);
      System.out.println("connected");
      try (BufferedWriter bw =
              new BufferedWriter(
                      new OutputStreamWriter(
                              socket.getOutputStream())))
      {  
        bw.write("GETCAR\n");
        bw.flush();
        System.out.println("send GETCAR");
      }
      try(BufferedReader br = 
              new BufferedReader(
                new InputStreamReader(
                  socket.getInputStream())))
      {
        if(!br.ready())
          Thread.sleep(700);
        String response = br.readLine();
        System.out.println("received response: " + response);
        receivedCar = response.split("-");
        System.out.println(receivedCar[0] + " " + receivedCar[1]);
        carlist.addCar(new Car(receivedCar[0],receivedCar[1]));
        clm.fireTableDataChanged();
      }
    }
    catch(Exception ex)
    {
      clm.fireTableDataChanged();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollCarTable = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("Get a car");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setLayout(new java.awt.GridLayout(1, 0));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {"AUDI", "A3"},
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String []
      {
        "Marke", "Typ"
      }
    ));
    jScrollCarTable.setViewportView(jTable1);

    jPanel2.add(jScrollCarTable);

    getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    getCar();
    clm.fireTableDataChanged();
  }//GEN-LAST:event_jButton1ActionPerformed


  /**
   * @param args the command line arguments
   */
  public static void main (String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run ()
      {
        new GUIClient().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollCarTable;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables

}
